### ISSUE TITLE
Add a photo/avatar

### ISSUE THREAD

**Issue by VladT-PM** [it-volunteers-ukraine/ChariERP#115]
#### Link to the page:
https://www.figma.com/design/al3AkjUmEzr5QEJjKIKkOm/Chari-New?node-id=5077-47025&t=d3TEiCBCU9StLqln-4
___

Consists of:

1. Picture / Зображення
The “Photo” icon by default looks like:
![image-20240627-094017](https://github.com/user-attachments/assets/6758fdf9-c83f-4922-aab1-afbe2f4acd58)

2. Hover to Show Camera Icon
When the user hovers over the default photo icon, the "camera" icon appears:

![Untitled](https://github.com/user-attachments/assets/699be3f6-fc2e-42d7-8ce1-42601f224fd4)

3. Uploading a Photo
By clicking on the “camera” icon, a file selection window opens.
Supported formats: jpg, jpeg, png
Maximum size: 5 MB
You can attach only 1 file.
The file can be added with any symbols.

Example of an uploaded photo:
![image-20240627-094508](https://github.com/user-attachments/assets/f4653c3b-7a53-46f2-8e32-8eb24a91078c)

4. Replacing or Deleting a Photo
- If the photo has been uploaded, it is possible to replace it or delete it while filling out the form:
![image-20240627-094159](https://github.com/user-attachments/assets/c8bf506e-366b-41b5-998c-b58d106f013d)

- By clicking on the cross "x" icon, the downloaded photo is deleted and returned to the default "Photo" icon state:
![image-20240627-094017](https://github.com/user-attachments/assets/380ff8e8-3caf-4146-8649-2fe28864b5ac)

5. Automatic Photo Generation
If no photo was added or a previously uploaded photo was deleted, then after submitting the form, the photo is generated automatically using the first two letters of the First Name and Last Name. Example: Artem Bondarenko / Артем Бондаренко:
![image-20240627-094102](https://github.com/user-attachments/assets/cd3bf44d-7522-4ec7-a762-7f178c4bcf8b)

**Comment by Evgeniy1283** [comment]
Hello! please add a link to stage c for testing this task
