### ISSUE TITLE
UI registration form: size font doesn't match the layout (1920,1440,992,768)

### ISSUE THREAD

**Issue by VladT-PM** [it-volunteers-ukraine/ChariERP#124]
**Environment**

**Desktop (please complete the following information)**
- OS: Windows 10 Pro v. 22H2 
- Browser: Google Chrome (v.125.0.6422.113). Mozilla Firefox  (127.0.2 (64-біт))

**Pre-conditions**
https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up page is opened

**Description**
Font size doesn't match the layout for EN, UA languages and for all screen resolutions: Desktop 1920, Desktop1440, Tablet 992, Tablet 768,  for text: 
- In Ukrainian (in accordance with the Charter)For example: Public organization 'LIVE'
- To download the document, click on the paperclip icon or the 'Download file' button. jpg, jpeg, png or pdf format. The maximum size is 5 MB.[ How to download the file.](https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up#)

**Steps to reproduce**
1. Set EN language in the application
2. Navigate to the registration form
3. Pay attention on size fonts for text:                                                                                                                                      
- In Ukrainian (in accordance with the Charter) For example: Public organization 'LIVE'
- To download the document, click on the paperclip icon or the 'Download file' button. jpg, jpeg, png or pdf format. The maximum size is 5 MB.[ How to download the file.](https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up#)

**Actual results**
Text: 
- In Ukrainian (in accordance with the Charter)For example: Public organization 'LIVE'
- To download the document, click on the paperclip icon or the 'Download file' button. jpg, jpeg, png or pdf format. The maximum size is 5 MB.[ How to download the file.](https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up#)

have size font - 16px in Google Chrome, Firefox browsers and for Desktop 1920, Desktop1440, Tablet 992, Tablet 768  screen resolutions

**Expected results**
Text: 
- In Ukrainian (in accordance with the Charter)For example: Public organization 'LIVE'
- To download the document, click on the paperclip icon or the 'Download file' button. jpg, jpeg, png or pdf format. The maximum size is 5 MB.[ How to download the file.](https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up#)    have size font - 14px  in Google Chrome, Firefox, Safari browsers and for Desktop 1920, Desktop1440, Tablet 992, Tablet 768 screen resolutions

**Screenshots** 
![2024-07-02_13h58_29](https://github.com/user-attachments/assets/b2c680ef-52a9-41b0-8540-ab5c1df91b1c)
![2024-07-02_13h59_03](https://github.com/user-attachments/assets/222b19ea-cb6c-45b5-9f1b-f40a45c4b455)
![2024-07-02_13h59_45](https://github.com/user-attachments/assets/2e86c2d7-507d-4d9b-a0ee-66c827819389)
![2024-07-02_14h01_26](https://github.com/user-attachments/assets/0f997183-f2ac-412e-b74e-d523e3aa29b5)
![2024-07-02_14h05_14](https://github.com/user-attachments/assets/3411c83a-5906-4843-9d48-e3d8c277afa1)
![2024-07-02_14h06_22](https://github.com/user-attachments/assets/3e200a70-f618-4ec9-a3fc-bd06bb6ee471)
![2024-07-02_14h09_52](https://github.com/user-attachments/assets/a74765a7-fe58-4109-9e36-599410ab3166)
![2024-07-02_14h11_07](https://github.com/user-attachments/assets/708ce744-876a-4195-b03d-34d9d6ce3aa9)

**Comment by DavydiukDmytro** [comment]
Close by
https://github.com/it-volunteers-ukraine/ChariERP/commit/8bdcf54acea0fc7d269d270cf71297f97bd0251a
