### ISSUE TITLE
UI registration form ("CONTACT INFORMATION" and "Media" sections): size font doesn't match the layout (375)

### ISSUE THREAD

**Issue by VladT-PM** [it-volunteers-ukraine/ChariERP#127]
**Environment**

**Desktop (please complete the following information)**
OS: Windows 10 Pro v. 22H2
Browser: Google Chrome (v.126.0.6478.127). Mozilla Firefox (127.0.2)

**Pre-conditions**
https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up  page is opened

**Description**
Font size doesn't match the layout for EN, UA languages and for all screen resolutions mobile 375 for text:
- For example: Manager, IA, Accountant, etc.
- For example: +38(050)123-45-36 or +38(044)222-22-33
- This email address will be your login. You will receive a letter to the specified email address regarding the results of processing your registration request.
- Include the organization's website.For example: https://gozhivi.com.ua/
- Add links to social media (Facebook, Instagram, LinkedIn, TikTok, Youtube, etc.). For example: https://www.facebook.com/gozhivi 

**Steps to reproduce**
1. Set EN language in the application
2. Navigate to the registration form
3. Pay attention on size fonts for text: 
- For example: Manager, IA, Accountant, etc.
- For example: +38(050)123-45-36 or +38(044)222-22-33
- This email address will be your login. You will receive a letter to the specified email address regarding the results of processing your registration request.
- Include the organization's website.For example: https://gozhivi.com.ua/ 
- Add links to social media (Facebook, Instagram, LinkedIn, TikTok, Youtube, etc.). For example: https://www.facebook.com/gozhivi  

**Actual results**
Text: 
- For example: Manager, IA, Accountant, etc.
- For example: +38(050)123-45-36 or +38(044)222-22-33
- This email address will be your login. You will receive a letter to the specified email address regarding the results of processing your registration request.
- Include the organization's website.For example: https://gozhivi.com.ua/  
- Add links to social media (Facebook, Instagram, LinkedIn, TikTok, Youtube, etc.). For example: https://www.facebook.com/gozhivi

   have size font - 16px in Google Chrome, Firefox browsers and for mobile 375 screen resolutions

**Expected results**
Text: 
- For example: Manager, IA, Accountant, etc.
- For example: +38(050)123-45-36 or +38(044)222-22-33
- This email address will be your login. You will receive a letter to the specified email address regarding the results of processing your registration request.
- Include the organization's website.For example: https://gozhivi.com.ua/   
- Add links to social media (Facebook, Instagram, LinkedIn, TikTok, Youtube, etc.). For example: https://www.facebook.com/gozhivi 

have size font - 13px in Google Chrome, Firefox, Safari browsers and for mobile 375 screen resolutions

**Screenshots** 
![example stage](https://github.com/user-attachments/assets/6eb0e92f-7009-42b6-bdc8-6bd2047fc650)
![example](https://github.com/user-attachments/assets/93a42dd6-b4d2-4ee4-8bcf-dce048383724)

**Comment by DavydiukDmytro** [comment]
Close by
https://github.com/it-volunteers-ukraine/ChariERP/commit/8bdcf54acea0fc7d269d270cf71297f97bd0251a
