### ISSUE TITLE
UI registration form (''CONTACT INFORMATION" and "Media" section): size font doesn't match the layout (1920,1440,992,768)

### ISSUE THREAD

**Issue by VladT-PM** [it-volunteers-ukraine/ChariERP#130]
**Environment**

**Desktop (please complete the following information)**
OS: Windows 10 Pro v. 22H2
Browser: Google Chrome (v.126.0.6478.127). Mozilla Firefox (127.0.2)

**Pre-conditions**
https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up  page is opened

**Description**
Font size doesn't match the layout for EN, UA languages and for all screen resolutions: Desktop 1920, Desktop1440, Tablet 992, Tablet 768, for text: 
- For example: Manager, IA, Accountant, etc.
- For example: +38(050)123-45-36 or +38(044)222-22-33
- This email address will be your login. You will receive a letter to the specified email address regarding the results of processing your registration request.
- Include the organization's website.For example: https://gozhivi.com.ua/  
- Add links to social media (Facebook, Instagram, LinkedIn, TikTok, Youtube, etc.). For example: https://www.facebook.com/gozhivi  

**Steps to reproduce**
1. Set EN language in the application
2. Navigate to the registration form
3. Pay attention on size fonts for text:
- For example: Manager, IA, Accountant, etc.
- For example: +38(050)123-45-36 or +38(044)222-22-33
- This email address will be your login. You will receive a letter to the specified email address regarding the results of processing your registration request.
- Include the organization's website.For example: https://gozhivi.com.ua/   
- Add links to social media (Facebook, Instagram, LinkedIn, TikTok, Youtube, etc.). For example: https://www.facebook.com/gozhivi   

**Actual results**
Text:
- For example: Manager, IA, Accountant, etc.
- For example: +38(050)123-45-36 or +38(044)222-22-33
- This email address will be your login. You will receive a letter to the specified email address regarding the results of processing your registration request.
- Include the organization's website.For example: https://gozhivi.com.ua/    
- Add links to social media (Facebook, Instagram, LinkedIn, TikTok, Youtube, etc.). For example: https://www.facebook.com/gozhivi    

have size font - 16px in Google Chrome, Firefox browsers and for Desktop 1920, Desktop1440, Tablet 992, Tablet 768 screen resolutions

**Expected results**
Text:
- For example: Manager, IA, Accountant, etc.
- For example: +38(050)123-45-36 or +38(044)222-22-33
- This email address will be your login. You will receive a letter to the specified email address regarding the results of processing your registration request.
- Include the organization's website.For example: https://gozhivi.com.ua/    
- Add links to social media (Facebook, Instagram, LinkedIn, TikTok, Youtube, etc.). For example: https://www.facebook.com/gozhivi    

have size font - 14px in Google Chrome, Firefox, Safari browsers and for Desktop 1920, Desktop1440, Tablet 992, Tablet 768 screen resolutions

**Screenshots** 
![example 768](https://github.com/user-attachments/assets/ac4abc57-2bba-4d5e-be7f-6cfba0f20ced)
![example 992](https://github.com/user-attachments/assets/80b31b87-78a3-4bdf-a70b-6d8beef795fa)
![example 1440](https://github.com/user-attachments/assets/60f0f7fe-159a-48bc-a751-fdb7a7024b97)
![example 1920](https://github.com/user-attachments/assets/0717f12a-5ea9-4f3f-8787-931ae6f80583)
![example stage 768](https://github.com/user-attachments/assets/e52b945a-69b8-45fc-a265-afb984d3927d)
![example stage 992](https://github.com/user-attachments/assets/ae1309e0-7330-45b0-92c7-9eb8a1787d2c)
![example stage 1440](https://github.com/user-attachments/assets/f3131c4d-7e67-4e9f-9247-fd176ae5f22e)
![example stage 1920](https://github.com/user-attachments/assets/df2e25bd-6a35-4cbf-8ce0-694855085a0b)

**Comment by DavydiukDmytro** [comment]
Close by
https://github.com/it-volunteers-ukraine/ChariERP/commit/8bdcf54acea0fc7d269d270cf71297f97bd0251a
