### ISSUE TITLE
UХ SIGN IN: Spaces in the login and password input fields (1920,1440,992,768,375)

### ISSUE THREAD

**Issue by KatyPupa** [it-volunteers-ukraine/ChariERP#136]
**Environment
Desktop:**
OS: macOS Sonoma 14.5
Browser: Safari Version 17.5

**Mobile:**
OS: iOS 17.5.1 
Browser: Safari Version 17.5

**Pre-conditions:**

https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-in - page is opened

**Description:**

A critical bug allows users to input spaces in the "email" and "password" fields, posing security risks.
 (for all screen resolutions: Desktop 1920, Desktop1440, Tablet 992, Tablet 768, Mobile 375.)

**Steps to reproduce:**

1. Open the login form.
2. Enter a username with spaces before and after login (e.g., "               BBB@D.f                ").
3. Enter a password with spaces before and after the password (e.g., "            @@@@@@@@         ").
4. Click the "Sign in" button.

**Actual results:**

The system accepts usernames and passwords with spaces.

**Expected results:**
An error message should appear indicating invalid input due to spaces in the "username" and "password" fields.

**Screenshots:**
<img width="900" alt="Знімок екрана 2024-07-29 о 20 02 03" src="https://github.com/user-attachments/assets/d0b477e2-3bd7-41e6-8f76-ae56fec35683">

https://github.com/user-attachments/assets/4ff35eb5-a58b-44fc-9c10-5f517b9a0436

**Comment by VladDot** [comment]
it`s correct behavior
