### ISSUE TITLE
То сreate a radio button

### ISSUE THREAD

**Issue by VladT-PM** [it-volunteers-ukraine/ChariERP#151]

**Comment by Evgeniy1283** [comment]
What button are you talking about, insert a link to the figma or add a picture

**Comment by VladT-PM** [comment]
> What button are you talking about, insert a link to the figma or add a picture

https://www.figma.com/design/al3AkjUmEzr5QEJjKIKkOm/Chari-New?node-id=4774-54633&t=bkCvcoZVvtTLKWEW-4
