### ISSUE TITLE
Create the header

### ISSUE THREAD

**Issue by rpkyrych** [it-volunteers-ukraine/ChariERP#17]
Create the header with all possible dimensions

https://www.figma.com/file/bwR3wSSptI35S27sC2bjNL/Chari?type=design&node-id=127-14717&mode=design&t=e5eImzHqXUPwBvyy-4

**Comment by asaziua** [comment]
**Design** 
Header component with 1920, 1440, 992, 768, 375 sizes. 
https://www.figma.com/file/bwR3wSSptI35S27sC2bjNL/Chari?type=design&node-id=127-14717&mode=design&t=e5eImzHqXUPwBvyy-4
