### ISSUE TITLE
SIGN UP: validation of the USREOU / Full name of the organization field (1920,1440,992,768,375)

### ISSUE THREAD

**Issue by alinaivanishcheva** [it-volunteers-ukraine/ChariERP#193]
**Environment**

**Desktop (please complete the following information)**
 - OS: Windows 10 Pro v. 22H2
 - Browser: Google Chrome (v.125.0.6422.113). Mozilla Firefox (127.0.2 (64-біт))

**Smartphone (please complete the following information)**
 - iPhone14
 - iOS 17.5.1
 - Google Chrome

**Pre-conditions**
https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up - page is opened

**Description**
1. The 8-value USREOU code is not fully recorded when the value starts with ‘0’.
2. In the "Full name of the organization" field, spaces from the beginning of the field are not deleted (left trim)  'and extra spaces in the middle of the ‘normalize spaces’ field
for all screen resolutions: Desktop 1920, Desktop1440, Tablet 992, Tablet 768, Mobile 375.

**Steps to reproduce**
1. Navigate to the sign up page.
3. Enter a few spaces at the start of the field, a few spaces in the middle of the field.
4. Enter 8 numbers of the USREOU code starting with ‘0’.
5. Then fill in the form valid values.
6. Click submit form.
7. Pay attention on text in the field  "Full name of the organization"  in requests.
8. Pay attention on code in the field  " the USREOU"  in requests.

**Actual results**
1. The 8-value USREOU code is not fully recorded when the value starts with ‘0’.
2. In the "Full name of the organization" field, spaces from the beginning of the field are not deleted (left trim)  'and extra spaces in the middle of the ‘normalize spaces’ field
for all screen resolutions: Desktop 1920, Desktop1440, Tablet 992, Tablet 768, Mobile 375.

**Expected results**
1. The 8-value USREOU code recorded when the value starts with ‘0’.
2. In the "Full name of the organization" field there is a function left trim and normalize spaces.
for all screen resolutions: Desktop 1920, Desktop1440, Tablet 992, Tablet 768, Mobile 375.

**Screenshots** 
![2024-09-16_13h57_22](https://github.com/user-attachments/assets/0de88769-9fa4-4fc6-8586-fae338e8902c)
![2024-09-16_13h58_42](https://github.com/user-attachments/assets/1d180c3c-a1e3-4804-9344-fbced06616a7)
![2024-09-17_09h21_19](https://github.com/user-attachments/assets/a88101bc-beb7-42aa-95b9-a2161c5b1c0c)

**Comment by Wolshebnik** [comment]
will be fix in [#123](https://github.com/it-volunteers-ukraine/ChariERP/issues/123)
