### ISSUE TITLE
UI SIGN UP: incorrect translate, grammatical mistakes (1920,1440,992,768,375)

### ISSUE THREAD

**Issue by alinaivanishcheva** [it-volunteers-ukraine/ChariERP#194]
**Environment**

**Desktop (please complete the following information)**
 - OS: Windows 10 Pro v. 22H2
 - Browser: Google Chrome (v.125.0.6422.113). Mozilla Firefox (127.0.2 (64-біт))

**Smartphone (please complete the following information)**
 - iPhone14
 - iOS 17.5.1
 - Google Chrome

**Pre-conditions**
https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up - page is opened

**Description**
1. Different translations of the name ‘EDRPOU’ or ‘USREOU’ in requests page for the SuperAdmin dashboard.
2. Grammatical mistakes in Ukrainian on the registration page (an example in the photo).
3. Change the translation of the buttons to ‘Ukrainian’ for the Ukrainian localization of ‘accept’ and ‘ decline’  - " прийняти" та " відхилити".
4.  Grammatical mistakes in Ukrainian "Заявка успішно відправле**нн**а" 

**Steps to reproduce**
1. Navigate to the sign up page.
2. Pay attention on text.

**Actual results**
1. Different translations of the name ‘EDRPOU’ or ‘USREOU’ in requests page for the SuperAdmin dashboard.
2. Grammatical mistakes in Ukrainian on the registration page (an example in the photo).
3. Change the translation of the buttons to ‘Ukrainian’ for the Ukrainian localization of ‘accept’ and ‘ decline’  - " прийняти" та " відхилити".

**Expected results**
Translation of words matches the requirements, no grammatical mistakes.

**Screenshots** 
![2024-09-17_10h18_12](https://github.com/user-attachments/assets/c8e44d30-6fec-4c5e-be37-2fa4a70340de)
![2024-09-17_10h18_40](https://github.com/user-attachments/assets/c39be7cb-8de3-4bf9-a3d7-2e18164f7a6d)
![2024-09-17_10h33_54](https://github.com/user-attachments/assets/4283f8f0-0d5b-4fd4-9236-9d630781eeb5)
![2024-09-17_10h37_58](https://github.com/user-attachments/assets/3d2f6e2d-e0a8-456c-baca-99f6532d4ffb)
![2024-09-17_10h46_23](https://github.com/user-attachments/assets/4e5ccf20-5509-41ee-a3a3-2315d98ce344)

![Image](https://github.com/user-attachments/assets/19b1d4fb-6b1d-4784-b201-d7cc5aaf7885)

**Comment by KatyPupa** [comment]
I propose : "Дана електронна адреса буде логіном. Ви отримаєте лист на вказану електронну адресу щодо результатів обробки вашого запиту на реєстрацію."

**Comment by alinaivanishcheva** [comment]
@VladT-PM  прохання передати дизайнерам внести зміни в макеті у фігмі.

**Comment by Wolshebnik** [comment]
![Image](https://github.com/user-attachments/assets/a4a91149-f3b5-4780-a0ba-1e095a7c4cfa)
deleted the link. We talked about this at the meet.

**Comment by Wolshebnik** [comment]
> I propose : "Дана електронна адреса буде логіном. Ви отримаєте лист на вказану електронну адресу щодо результатів обробки вашого запиту на реєстрацію."

I propose: Електронна адреса буде вашим логіном. Ви отримаєте лист на вказану електронну адресу з результатами обробки вашого запиту на реєстрацію.

**Comment by alinaivanishcheva** [comment]
the "decline" and ‘accept’ buttons are not translated in Ukrainian @Wolshebnik  
please fix )
![2024-10-05_12h09_32](https://github.com/user-attachments/assets/9110fe25-7fac-40b1-9530-11de880315cb)

**Comment by VladT-PM** [comment]
> the "decline" and ‘accept’ buttons are not translated in Ukrainian [@Wolshebnik](https://github.com/Wolshebnik) please fix ) ![2024-10-05_12h09_32](https://github.com/user-attachments/assets/9110fe25-7fac-40b1-9530-11de880315cb)

Hi,
Thanks.
@alinaivanishcheva, @Wolshebnik I suggest leaving it unchanged, since only the Super Admin on our side will use it.
If the other bugs are fixed, I suggest closing this bug.

**Comment by Wolshebnik** [comment]
closed
