### ISSUE TITLE
UI SIGN UP: non-compliance with the ‘trailing icon’ layout (1920,1440,992,768,375)

### ISSUE THREAD

**Issue by alinaivanishcheva** [it-volunteers-ukraine/ChariERP#195]
**Environment**

**Desktop (please complete the following information)**
 - OS: Windows 10 Pro v. 22H2
 - Browser: Google Chrome (v.125.0.6422.113). Mozilla Firefox (127.0.2 (64-біт))

**Smartphone (please complete the following information)**
 - iPhone14
 - iOS 17.5.1
 - Google Chrome

**Pre-conditions**
https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up - page is opened

**Description**
In the media section, in the fields ‘Internet page of the organization (website)’ / ‘Link to a social network’, there is no icon for clearing the field ( no ‘trailing-icon’ ) that doesn't match the layout for EN, UA languages and for all screen resolutions: Desktop 1920, Desktop1440, Tablet 992, Tablet 768, Mobile 375.

**Steps to reproduce**
1. Navigate to the sign up page.
2. Look at on the fields ‘Internet page of the organization (website)’ / ‘Link to a social network’

**Actual results**
In the media section, in the fields ‘Internet page of the organization (website)’ / ‘Link to a social network’, there is no icon for clearing the field ( no ‘trailing-icon’ ) that doesn't match the layout for EN, UA languages and for all screen resolutions: Desktop 1920, Desktop1440, Tablet 992, Tablet 768, Mobile 375.

**Expected results**
In the media section, in the fields ‘Internet page of the organization (website)’ / ‘Link to a social network’, there is icon for clearing the field ( no ‘trailing-icon’ ) that does match the layout for EN, UA languages and for all screen resolutions: Desktop 1920, Desktop1440, Tablet 992, Tablet 768, Mobile 375.

**Screenshots** 
![2024-09-17_11h17_12](https://github.com/user-attachments/assets/d4e551d4-ed52-43a9-861e-dd97aac832f9)
![2024-09-17_11h18_56](https://github.com/user-attachments/assets/e9d13a51-8073-4db0-b72b-a142a5498498)

**Comment by Wolshebnik** [comment]
correct behavior
