### ISSUE TITLE
SuperAdmin dashboard/ Header/ Incorrect page title of Requests, Declined, Organizations. 

### ISSUE THREAD

**Issue by KatyPupa** [it-volunteers-ukraine/ChariERP#212]
**Environment**

**Desktop **
OS: macOS Sonoma 14.5
Browser: Safari Version 17.5

**Pre-conditions**
https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up page is opened.
https://www.figma.com/design/al3AkjUmEzr5QEJjKIKkOm/Chari-New?node-id=4760-39039&t=2NBq4VALaGtqMqsp-

**Description**
The title of the page does not match the selected position in the sidebar and does not match the layout at all screen resolutions.

**Steps to reproduce**

1. Open the superadmin dashboard. 
2. Select "Organizations" in the sidebar. 
3. Check the name of the page opened on the table. 
4. Repeat the action with Requests, Declined. 

**Expected results**
The title of the page matches the selected position in the sidebar at all screen resolutions.

**Actual results**
The title of all pages is the same "Main page".  

**Screenshots**
<img width="1552" alt="Знімок екрана 2024-09-23 о 15 53 46" src="https://github.com/user-attachments/assets/8c4e19da-5d66-4391-abb7-e4bee33121e9">
<img width="1180" alt="Знімок екрана 2024-09-23 о 15 55 37" src="https://github.com/user-attachments/assets/0fefcbba-1b53-45aa-8599-fe24e6e15ffc">
<img width="845" alt="Знімок екрана 2024-09-23 о 16 18 43" src="https://github.com/user-attachments/assets/b2b3b565-142f-434e-a8f4-1a4d4463d2fc">
<img width="834" alt="Знімок екрана 2024-09-23 о 16 19 16" src="https://github.com/user-attachments/assets/e8afeae4-9076-4a03-afbf-0fede2585399">

**Comment by Wolshebnik** [comment]
fixed in the [#233](https://github.com/it-volunteers-ukraine/ChariERP/issues/233)
