### ISSUE TITLE
SuperAdmin dashboard/ The organization details information page (768 and 375 px). 

### ISSUE THREAD

**Issue by KatyPupa** [it-volunteers-ukraine/ChariERP#217]
**Environment**
**Desktop**
 - OS: macOS Sonoma 14.5
 - Browser  Safari  
 - Version 17.5

**Smartphone** 
 - Device:  iPhone 11
 - OS: iOS 17.6.1
 - Browser Safari
 - Version  17.6.1

**Pre-conditions**
- (https://www.figma.com/design/al3AkjUmEzr5QEJjKIKkOm/Chari-New?node-id=4704-24904&t=qjunhN9qnWAd2pKn-4)
- https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up page is opened.
- 
**Description**
The organization details information page for Requests, Declined, Organizations does not match the layout on 768 and 375 px adaptives.  

**Steps to reproduce**

1. Open the superadmin dashboard on 768 px and 375 px adaptive.
2. Select **"Requests"** in the sidebar and open any organization from the table.
3. Compare the display of the organization details page with the layout.
4. Repeat steps 2–3 for the **"Declined"** and **"Organizations"** sections.
5. Ensure each page matches the layout on both 768 px and 375 px adaptives.

**Actual results**
The organization details information page for Requests, Declined, Organizations does not match the layout on 768 and 375 px adaptives.  

**Expected results**
The organization details information page for Requests, Declined, Organizations matches the layout on 768 and 375 px adaptives.  

**Screenshots** 
<img width="570" alt="Знімок екрана 2024-09-24 о 17 39 18" src="https://github.com/user-attachments/assets/7b07e7d2-3d95-44bc-8c2e-02ea9a86e1e6">
<img width="901" alt="Знімок екрана 2024-09-24 о 18 10 01" src="https://github.com/user-attachments/assets/7593b292-05a5-46da-b7d6-cfb9b0dc21ce">
<img width="641" alt="Знімок екрана 2024-09-24 о 17 37 22" src="https://github.com/user-attachments/assets/61aa53f1-53fe-4439-aca3-6075475393ec">
<img width="619" alt="Знімок екрана 2024-09-24 о 17 38 13" src="https://github.com/user-attachments/assets/89369408-a0bc-4304-a6d1-1fd8f497965e">
<img width="634" alt="Знімок екрана 2024-09-24 о 17 38 29" src="https://github.com/user-attachments/assets/5890332e-41c1-4bbc-8169-57c34cac6b57">
![photo_2024-09-24 18 11 38](https://github.com/user-attachments/assets/39952c32-4c0c-4ef5-9fae-efa2d157d47e)
![photo_2024-09-24 18 11 43](https://github.com/user-attachments/assets/9d5ff9dc-5315-4fae-afdc-1f7848887d5a)

**Comment by VladDot** [comment]
This ticket will be done in 233
