### ISSUE TITLE
Acceptance of the request from the Organization after editing the data

### ISSUE THREAD

**Issue by KatyPupa** [it-volunteers-ukraine/ChariERP#223]
**Environment**

**Desktop **
OS: macOS Sonoma 14.5
Browser: Safari Version 17.5

**Pre-conditions**
https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-in page is opened.
The organization has been created and is located in the Requests section

**Description**

Acceptance of the request from the Organization after editing the data does not happen. 

**Steps to reproduce**
1. Select any organization from the list on the Requests page.
2. Change the email address to tester20@gmail.com. 
3. Save new data.  
4. Press the Accept button. 

**Actual results**
A message appears that the organization with this email is already registered.
In the database, this organization has the Pending status.    

**Expected results**
An organization with such a unique email is accepted and receives the status Accepted.

**Screenshots** 
<img width="825" alt="Знімок екрана 2024-09-28 о 11 47 26" src="https://github.com/user-attachments/assets/d51923e0-f427-41da-b068-bf595bbcc503">
<img width="840" alt="Знімок екрана 2024-09-28 о 11 48 04" src="https://github.com/user-attachments/assets/a7783247-7517-495a-8160-b8bbd5f6c73a">
<img width="1426" alt="Знімок екрана 2024-09-28 о 11 48 54" src="https://github.com/user-attachments/assets/03c9ab53-46e1-4eb8-9a39-ec19d9a46dd6">

**Comment by KatyPupa** [comment]
IT IS IMPOSSIBLE TO ACCEPT AN APPLICATION FROM THE organization:
Digital ocean: The message in the logs indicates an error MISSING_MESSAGE (missing translation for the key modal.successfulRegistration.firstPartText for the Ukrainian localization (ua).)

![photo_2024-10-02 15 30 18](https://github.com/user-attachments/assets/01fb7ccd-2de3-4e8d-b010-088af395e6df)
![photo_2024-10-02 15 30 32](https://github.com/user-attachments/assets/aef4f759-3cb3-42e4-ab21-65b88820656f)

**Comment by ASGladchenko** [comment]
Bug with registration error when email is already taken are fixed.

Mock bug will be fixed by @Kyslytsia
