### ISSUE TITLE
SuperAdmin dashboard/ display the login name in the header (1920,1440,992,768,375)

### ISSUE THREAD

**Issue by alinaivanishcheva** [it-volunteers-ukraine/ChariERP#266]
**Environment**

**Desktop (please complete the following information)**
- OS: Windows 10 Pro v. 22H2
 - Browser: Google Chrome (v.125.0.6422.113). Mozilla Firefox (127.0.2 (64-біт))

**Smartphone (please complete the following information)**
- iPhone14
 - iOS 17.5.1
 - Google Chrome

**Pre-conditions**
1. Use the following credentials for https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up:
login: it.volunteers.ukraine@gmail.com
pass: 3._O56!bA
2. https://chari-erp-dev-5jqgv.ondigitalocean.app/admin/requests -   page is opened.

**Description**
Display the login name in the header when the user enters the account for screen resolutions: Desktop 1920, Desktop1440, Tablet 992,Tablet 768, Mobile 375.

**Steps to reproduce**
1. Open the Requests page.
2. Click the Logo.
3. Pay attention on name login  

**Actual results**
Display name button "login in"  the header when the user enters the account for screen resolutions: Desktop 1920, Desktop1440, Tablet 992,Tablet 768, Mobile 375.

**Expected results**
Display the login name in the header when the user enters the account for screen resolutions: Desktop 1920, Desktop1440, Tablet 992,Tablet 768, Mobile 375.

**Screenshots** 

https://github.com/user-attachments/assets/16d6171c-bac2-49cb-acfd-4d03b1bedca8

**Comment by Wolshebnik** [comment]
I need a task for this

**Comment by DavydiukDmytro** [comment]
#311 I fixed it in this task

**Comment by alinaivanishcheva** [comment]
@DavydiukDmytro   Не бачу виправлень, будуть зміни ?
