### ISSUE TITLE
UI: Message about a canceled application doesn't have a support link 

### ISSUE THREAD

**Issue by Evgeniy1283** [it-volunteers-ukraine/ChariERP#267]
Environment

OS: Windows 10 Pro v. 22H2

Browser Google Chrome (v.125.0.6422.113). Mozilla Firefox (127.0.2 (64-біт))

**Pre-conditions**
- email used during registration - is open

**Description**
Message about a canceled application doesn't have a support link 

**Steps to reproduce**
1. Go to https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up to fill all fields with valid data
2. Login to the application pending approval as superadmin (https://chari-erp-dev-5jqgv.ondigitalocean.app/admin/requests)
3. Find your new organization and click the "Accept" button
4. Open the message that came to your email from Chari ERP
5. Pay attention on the next text: After verification of your data (within 48 business hours), you will receive an email to the specified email address .yevgenpavlov83@gmail.com with a login and password. If you have any questions, don't hesitate to contact us!

**Actual results**
Message about a canceled application doesn't have a support link 

**Expected results**
The cancellation message contains a link to support.

**Screenshots** 
[https://drive.google.com/file/d/1kWVDrzYbLOJvhgkdYEunEIg86Q25hz4k/view?usp=sharing](url)

**Comment by ASGladchenko** [comment]
Retest  please
