### ISSUE TITLE
UI:  Pop-up registration notification doesn't have a support link 

### ISSUE THREAD

**Issue by Evgeniy1283** [it-volunteers-ukraine/ChariERP#269]
**Environment**

OS: Windows 10 Pro v. 22H2

Browser Google Chrome (v.125.0.6422.113). Mozilla Firefox (127.0.2 (64-біт))

Pre-conditions

[email used during registration](https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up) - is open

Description
Pop-up registration notification doesn't have a support link 

Steps to reproduce

1. Go to https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up to fill all fields with valid data

3. Click "Submit form" button

4. Pay attention on the Pop-up registration notification 

Actual results
 Pop-up registration notification doesn't have a support link 

Expected results
Pop-up registration notification contains a link to support.

**Screenshots** 
[https://drive.google.com/file/d/17vDh5poQ5UziyxFiuxcsHoUWR4f1A707/view?usp=sharing](url)

**Comment by ASGladchenko** [comment]
re test please
