### ISSUE TITLE
UX: Declined page, Organization details information page on the decline requests: Clicking the "Accept' button on page "Declined", it is not possible to accept organization

### ISSUE THREAD

**Issue by Evgeniy1283** [it-volunteers-ukraine/ChariERP#271]
OS: Windows 10 Pro v. 22H2

Browser Google Chrome (v.125.0.6422.113). Mozilla Firefox (127.0.2 (64-біт))

Pre-conditions

https://chari-erp-dev-5jqgv.ondigitalocean.app/admin/declined -page is open

Description
Clicking the "Accept' button on page "Declined" and "Organization details information page on the decline requests", it is not possible to accept organization

Steps to reproduce

1) As super admin, select "Test all in Eng' organization. 
https://chari-erp-dev-5jqgv.ondigitalocean.app/admin/declined/670e8ed821b822860c6b4524
2) Click on the "Accept" button
3) Check the status on Devtools
4) Repeat all steps on the "organization details information page on the decline requests"

Actual results
Clicking the "Accept' button on page "Declined"and "Organization details information page on the decline requests", it is not possible to accept organization

Expected results
By clicking the Accept button on the "Declined" page, and "Organization details information page on the decline requests", the organization changes its status to accepted.
![Image](https://github.com/user-attachments/assets/1f27c5b4-fc69-4ad6-9ce6-3e6f44c4453f)

Video
https://github.com/user-attachments/assets/7952e8a1-f189-480d-81af-7b9663dc4635

**Comment by DavydiukDmytro** [comment]
This bug does not exist

**Comment by Evgeniy1283** [comment]
@DavydiukDmytro Try to accept the organization ("Test all in Eng" in Declined page) yourself, and you will understand everything
