### ISSUE TITLE
Date of registration of the organization is entered into the database incorrectly

### ISSUE THREAD

**Issue by KatyPupa** [it-volunteers-ukraine/ChariERP#272]
**Environment**
Desktop

OS: macOS Sonoma 14.5
Browser Safari
Version 17.5

**Pre-conditions**
https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up is opened. 

**Description**

Date of registration of the organization is entered into the database incorrectly (One day earlier). 

**Steps to reproduce**
1. Fill out the registration form with valid data.
2. In the Organization Registration Date field, enter the date 01. 01. 2023. 
3. Send the registration form.
4. Compare the date of registration on the site and in the Mongo database. 

**Actual results**
Registration date on the site - 01. 01. 2023
Registration date in the Mongo database - 31. 12. 2022

**Expected results**
All data on the site and in the database must be the same.

**Screenshots**
<img width="1129" alt="Знімок екрана 2024-10-15 о 16 00 19" src="https://github.com/user-attachments/assets/1e64262b-a9e4-45f6-a055-d0640cb084e5">

<img width="1404" alt="Знімок екрана 2024-10-15 о 15 59 06" src="https://github.com/user-attachments/assets/1c6d3ea8-ff4c-43df-8377-1da99e651ed6">

**Comment by Wolshebnik** [comment]
Maybe Roma fixed that.

**Comment by KatyPupa** [comment]
Not fixed yet.

![Image](https://github.com/user-attachments/assets/062f1078-1f8d-4dfd-b01f-b4bb10695f33)

![Image](https://github.com/user-attachments/assets/54b3f5ea-6b31-4fb5-9c5f-0cb784e72d17)

**Comment by rpkyrych** [comment]
@KatyPupa I've applied a code fix, but I still can't get the date to be stored in the GMT +03:00 zone (Kyiv).
That was the last thing I could apply and hope the bug will be fixed.

Previously I set that timezone directly into Mongo: 
![Image](https://github.com/user-attachments/assets/8eb6ca00-b2dc-4835-8a54-ff58ee9e98ba)

I also tried to set timezone directly as the environment variable, according to the documentation: https://docs.digitalocean.com/products/app-platform/how-to/manage-time-zone/

![Image](https://github.com/user-attachments/assets/43e2e6ba-8107-4076-b985-ba655b947e96)
but that didn't help as well.

The final solution for the problem that remains - is to set the timezone directly in the code for each specific save or update of related entities, but that would require more effort compared to the end benefits of the date display in Mongo.

@olha-kyr FYI

**Comment by KatyPupa** [comment]
Unfortunately.....![Image](https://github.com/user-attachments/assets/ed3d1ba5-cf3f-4aba-8cae-b13d4cdb7db9)
![Image](https://github.com/user-attachments/assets/93134751-5d36-44aa-8d1f-c42877a0956e)

**Comment by KatyPupa** [comment]
{"organizationData.dateOfRegistration": {"$gte": ISODate("2019-01-01T00:00:00Z"), "$lt": ISODate("2020-01-01T00:00:00Z")}} 
The request will return all documents registered during 2019. But we will not see in this list organizations registered on the 01st of the year. 
Since these statistics are relevant only for Super Admin, it is possible to postpone the solution of this problem.
