### ISSUE TITLE
Invalid file format in an organization that is already registered

### ISSUE THREAD

**Issue by KatyPupa** [it-volunteers-ukraine/ChariERP#275]
**Environment**
Desktop
OS: macOS Sonoma 14.5
Browser Safari
Version 17.5

**Pre-conditions**
An organization with a valid file in the certificate of entry into the register has been created.
https://chari-erp-dev-5jqgv.ondigitalocean.app/admin/requests page is opened. 

**Description**
A valid file format when registering an organization opens on the Super Admin page as invalid. 

**Steps to reproduce**
1. Go to the page of detailed information about the created organization.
2. Click the Accept button and Yes
3. Look at the format of the attached file
4. Delete this file and add the same file.
5. Click the Accept button and Yes. 

**Actual results**
A valid file format when registering an organization opens on the Super Admin page as invalid. After deleting it and replacing it with the same file, the system accepts the Organization. The file is again displayed as invalid.

**Expected results**
If the file was accepted by the system during registration as valid, it should be displayed on the details page as valid.

**Screenshots** 
<img width="1151" alt="Знімок екрана 2024-10-17 о 13 08 30" src="https://github.com/user-attachments/assets/7439fb4f-4f4f-46eb-8490-528b0c9b514e">
<img width="1910" alt="Знімок екрана 2024-10-17 о 13 09 09" src="https://github.com/user-attachments/assets/c7ef621c-21ca-4d91-a3bb-7df02414139f">
<img width="1718" alt="Знімок екрана 2024-10-17 о 13 09 40" src="https://github.com/user-attachments/assets/ef3cae71-c5cc-4dd9-88ad-36be9dbdc3e5">
<img width="1768" alt="Знімок екрана 2024-10-17 о 13 10 26" src="https://github.com/user-attachments/assets/abe6e1b3-c1fc-4d4d-9897-52fafc96877e">
<img width="1701" alt="Знімок екрана 2024-10-17 о 13 11 40" src="https://github.com/user-attachments/assets/f9bafaa9-890c-4868-8e59-0ec6ad75c127">
<img width="1669" alt="Знімок екрана 2024-10-17 о 13 39 32" src="https://github.com/user-attachments/assets/50b93f19-9b7b-4731-8fbb-f7a7738b83c2">
<img width="1746" alt="Знімок екрана 2024-10-17 о 13 41 22" src="https://github.com/user-attachments/assets/e2565c2c-ca43-42bf-bfc5-88b473e0b948">
<img width="1780" alt="Знімок екрана 2024-10-17 о 13 42 12" src="https://github.com/user-attachments/assets/abff6ed2-f621-431e-a8a2-9e5e854f0558">

**Comment by Wolshebnik** [comment]
Check it, work correct

**Comment by KatyPupa** [comment]
Checked, does not work correctly.
[Запис екрана 2024-11-12 о 16.45.27.zip](https://github.com/user-attachments/files/17719080/2024-11-12.16.45.27.zip)
