### ISSUE TITLE
SuperAdmin dashboard/ "btn_arrow_right" is out of bounds screen resolution 375 px

### ISSUE THREAD

**Issue by alinaivanishcheva** [it-volunteers-ukraine/ChariERP#286]
**Environment**

**Smartphone (please complete the following information)**
iPhone14
iOS 17.5.1
Google Chrome

**Pre-conditions**
Login to the site is done by Superadmin:
login: [it.volunteers.ukraine@gmail.com](mailto:it.volunteers.ukraine@gmail.com)
pass: 3._O56!bA
https://chari-erp-dev-5jqgv.ondigitalocean.app/admin/requests - page is opened

**Description**
The "btn_arrow_right" is out of bounds screen resolution 375 px when more 10 page. (for requests, declined, organizations pages)

**Steps to reproduce**
1. Go to the requests page.
2. Cklick on number page 1.2.3.4.5.6 one by one.
3. Observe the "btn_arrow_right" 

**Actual results**
The "btn_arrow_right" is out of bounds screen resolution 375 px when more 10 page.

**Expected results**
The "btn_arrow_right" does matches the layout for 375px  (for requests, declined, organizations pages)

**Screenshots** 

![2024-10-23_23h29_09](https://github.com/user-attachments/assets/5c1d3b04-0bfb-4123-a60a-4dcb4469ab02)
![5246709848563901202 (1)](https://github.com/user-attachments/assets/47da4dd9-edde-45a5-8aca-e21a848ed42e)

https://github.com/user-attachments/assets/dd909b90-4d24-4e29-bb9a-837bb26c5ee0

**Comment by KatyPupa** [comment]
The pagination is not located according to the layout at a resolution of 768 pixels. 
Expected result: Pagination on the tablet and mobile is located and aligned in the center regardless of the number of pages.
<img width="744" alt="Знімок екрана 2024-10-29 о 12 38 38" src="https://github.com/user-attachments/assets/1592a497-ceb8-46a8-8809-14c1ed1d9e49">
<img width="730" alt="Знімок екрана 2024-10-29 о 15 45 37" src="https://github.com/user-attachments/assets/fa638115-8a9f-4cda-8c15-8dc9577564cb">

**Comment by Wolshebnik** [comment]
Estimate 4 hours
add 2 string code
