### ISSUE TITLE
Errors in the Media section on the Organization detailed information page

### ISSUE THREAD

**Issue by KatyPupa** [it-volunteers-ukraine/ChariERP#289]
**Environment**
Desktop
OS: macOS Sonoma 14.5
Browser Safari
Version 17.5

Smartphone
Device: iPhone 11
OS: iOS 17.6.1
Browser Safari
Version 17.6.1

**Pre-conditions**

https://chari-erp-dev-5jqgv.ondigitalocean.app/admin/requests page is opened.
The organization "Alina 23102024" from the Requests page. (Any organization with completed data in the media section) is opened. 

**Description**

Errors in the Media section on the organization details information page on the Requests, Declined, Organizations pages. 

**Steps to reproduce**

1. In the Media section, click on any link.
2. Click on the free space in front of the Delete Field button.
3. Look at the Button "+ Add another link" in EN localization. 
4. Look at the error messages.

**Actual results**
1. All links are not clickable. There is no redirect to the page. 
2. Clicking on the space in front of the Delete button removes the field from above.
3. The button has a name "+ Add more links". 
4. "Required field", False validation (with https)

**Expected results**
1. After clicking on the link in the media section, the page is redirected to this link.
2. Deleting a field occurs only when you click the Delete Field button. 
3. According to the requirements, the button has a name "+ Add another link". 
4.Fields in the Media section are not required. Valid data is accepted. 

**Screenshots**
<img width="535" alt="Знімок екрана 2024-10-25 о 16 08 39" src="https://github.com/user-attachments/assets/28c527fa-5ffe-4f8f-afa8-d5149b31b610">

https://github.com/user-attachments/assets/100f4552-b1e4-42aa-8119-a9720a6bfa4e

<img width="1030" alt="Знімок екрана 2024-10-28 о 17 16 34" src="https://github.com/user-attachments/assets/ef6d762c-418c-4594-95b2-bb9756d227fe">
![photo_2024-10-28 17 18 04](https://github.com/user-attachments/assets/23adbba8-c560-4e4b-b1f1-db79752a6bbe)

**Comment by Wolshebnik** [comment]
![Image](https://github.com/user-attachments/assets/5a240fba-9749-499a-8741-e2e53dcfd39a)

1. Not clickable
2. Fixed
3. ?????
4. Fexed

**Comment by KatyPupa** [comment]
1. Not clickable - OK
2. No Fixed

https://github.com/user-attachments/assets/e34ffb9c-5552-458d-8e3d-af6ee7241e0c

3. Let's change the requirements to The button has a name "+ Add more links". - OK
4. No Fixed
![Image](https://github.com/user-attachments/assets/8d8b00f4-efc2-40b1-9a24-9c16a2630458)
![Image](https://github.com/user-attachments/assets/911a90ca-7a9c-4030-a9c4-705a879e4cb2)

**Comment by KatyPupa** [comment]
![Image](https://github.com/user-attachments/assets/6ae0833b-9e1a-4f6a-a567-e4133376773e)

Input: Media / Media fields are not required.

**Comment by KatyPupa** [comment]
![Image](https://github.com/user-attachments/assets/3e8ef9d9-83b2-4168-a1a3-e0a42e756ca7)
Accepts an address that does not start with https

**Comment by VladDot** [comment]
This is normal behavior

Each subsequent input causes an error if the previous input is empty, except for the first one.
