### ISSUE TITLE
UX: Requests, Declined, Organizations pages: The copy button doesn`t have a hover function on all  Super_admin pages (All res)

### ISSUE THREAD

**Issue by Evgeniy1283** [it-volunteers-ukraine/ChariERP#290]
**Environment**
OS: Windows 10 Pro v. 22H2
Browser Google Chrome (v.125.0.6422.113). Mozilla Firefox (127.0.2 (64-біт))

**Pre-conditions**

https://chari-erp-dev-5jqgv.ondigitalocean.app/admin/requests - is open

**Description**
The copy button doesn`t have a hover function on all  Super_admin pages (All res)

**Steps to reproduce**
1. Go to https://chari-erp-dev-5jqgv.ondigitalocean.app/admin/requests page
2. Hover your mouse over the copy button
3. Repeat step two for all subsequent pages:
- https://chari-erp-dev-5jqgv.ondigitalocean.app/admin/declined
- https://chari-erp-dev-5jqgv.ondigitalocean.app/admin/organizations

**Actual results**
The copy button doesn`t have a hover function on all  Super_admin pages (All res)

**Expected results**
The copy button has a hover feature on all Super_admin pages (all res).

**Screenshots** 

https://github.com/user-attachments/assets/d58b04b2-0b4b-4f64-a1a7-26a9aeac5c93

**Comment by KatyPupa** [comment]
On the pages of detailed information about the organization does not appear a pop-up message "Copied to clipboard". 
States Copy buttons are not made according to the layout. (https://www.figma.com/design/al3AkjUmEzr5QEJjKIKkOm/Chari-New?node-id=8935-36725&t=fJoS9jkgeSI1NjTG-4)

<img width="255" alt="Знімок екрана 2024-10-28 о 17 42 07" src="https://github.com/user-attachments/assets/477b74ba-804b-42ad-bc76-3d7a79352abb">
<img width="263" alt="Знімок екрана 2024-10-28 о 17 42 37" src="https://github.com/user-attachments/assets/de576a5d-9bbb-4a57-bd91-c2a706b00118">
<img width="1416" alt="Знімок екрана 2024-10-28 о 17 46 26" src="https://github.com/user-attachments/assets/d3a262c3-17bc-44b1-aff2-843f54de5dea">
<img width="631" alt="Знімок екрана 2024-10-28 о 17 50 04" src="https://github.com/user-attachments/assets/62675eeb-e969-4ee8-9600-af613691aaed">
<img width="649" alt="Знімок екрана 2024-10-28 о 17 50 18" src="https://github.com/user-attachments/assets/a1fad0e9-3caf-4f52-a450-6d4a7c8c1758">


https://github.com/user-attachments/assets/2f0be4ff-ac46-4905-bfad-a8abfac5e74c

**Comment by Evgeniy1283** [comment]
https://github.com/user-attachments/assets/307398fa-d881-4566-8591-cdea2535ec86
![Image](https://github.com/user-attachments/assets/644867f0-4c4e-41cf-bdf4-3061b79906f4)

You should add another state "active" when the button is clicked. The button will change color to green

**Comment by Evgeniy1283** [comment]
Sorry, Danylo, this information is for you, not for Andrii!

**Comment by Evgeniy1283** [comment]
Unfortunately, I forgot to mention the fourth status, when the field is empty, the copy button becomes dark and inactive
![385383696-644867f0-4c4e-41cf-bdf4-3061b79906f4](https://github.com/user-attachments/assets/e265fcd4-eb0b-4213-afa3-c919da1e5c89)

**Comment by cloudmenson** [comment]
Added update. Now if there is no text in the field, the icon is gray and the cursor is disabled
