### ISSUE TITLE
Requests page/ Pop up DECLINE font size doesn't match the layout (1920.1440.992.768.375) 

### ISSUE THREAD

**Issue by alinaivanishcheva** [it-volunteers-ukraine/ChariERP#309]
Environment

Desktop 
OS: Windows 10 Pro v. 22H2
Browser: Google Chrome (v.125.0.6422.113). Mozilla Firefox (127.0.2 (64-біт))

Smartphone 
iPhone14
iOS 17.5.1
Google Chrome

Pre-conditions
-Use the following credentials for https://chari-erp-dev-5jqgv.ondigitalocean.app/sign-up:
login: [it.volunteers.ukraine@gmail.com](mailto:it.volunteers.ukraine@gmail.com)
pass: 3._O56!bA
https://chari-erp-dev-5jqgv.ondigitalocean.app/admin/requests - page is opened.

**Description**
1. On pop-up DECLINE  for screen resolutions: Desktop 1920, Laptop 1440, Tablet 992, Tablet 768, Mobile 375: On pop-up DECLINE  the font doesn't match the layout.
2. On pop-up DELITE  the font doesn't match the layout.

**Steps to reproduce**
1. Open the superadmin dashboard.
2. Select "Requests" in the sidebar and click the button DECLINE.
3. Look at the font

**Actual results**
On pop-up DECLINE  for screen resolutions: Desktop 1920, Laptop 1440, Tablet 992, Tablet 768, Mobile 375:
On pop-up DECLINE  the font doesn't match the layout.
On pop-up DELITE  the font doesn't match the layout.

**Screenshots** 

![2024-11-07_23h19_10](https://github.com/user-attachments/assets/99be8587-3ac8-4632-8273-868ef0b71e40)
![2024-11-07_23h32_35](https://github.com/user-attachments/assets/43a12f7d-cbb3-4d83-85c8-acec78ce9a60)
![2024-11-09_19h49_34](https://github.com/user-attachments/assets/e9672c3d-0332-492f-b31a-8f2b9e8cb799)
![2024-11-09_19h52_55](https://github.com/user-attachments/assets/441077f0-08b1-49ae-8d9a-45f735222359)
![Image](https://github.com/user-attachments/assets/026c343e-ae99-45ff-85d3-25d91a21a221)
![Image](https://github.com/user-attachments/assets/ce9df45e-456b-468e-8196-0f446df0bc31)

**Comment by DavydiukDmytro** [comment]
#311 I fixed it in this task
