### ISSUE TITLE
Test Contact Page

### ISSUE THREAD

**Issue by VladT-PM** [it-volunteers-ukraine/ChariERP#321]
Test Contact Page
Link to the page:
https://www.figma.com/design/al3AkjUmEzr5QEJjKIKkOm/Chari-New?node-id=6804-45516&t=MCqwu5g1IlRIhJa4-4

Not pixel perfect
Please link the bug to the milestone it relates to.

The feedback form should be like this.
After clicking the "Send form" / "Відправити форму" button and successfully sending (or not) the form, a notification (toast message) should appear to inform the user that the form was sent successfully.

Additionally, the submitted form should be delivered to the email: [it.volunteers.ukraine@gmail.com] (or any other for testing)

The delivered letter should look something like this layout:
![Image](https://github.com/user-attachments/assets/75c1964f-f899-474e-999e-3e4b496c5cc5)

**Comment by alinaivanishcheva** [comment]
@VladT-PM сторінка контакти перевірена без додаткової таски на чекбокс "політика конфіденційності" під контактною формою.

**Comment by VladT-PM** [comment]
> [@VladT-PM](https://github.com/VladT-PM) сторінка контакти перевірена без додаткової таски на чекбокс "політика конфіденційності" під контактною формою.

Hi,
Great, thanks a lot for the information!

**Comment by VladT-PM** [comment]
> [@VladT-PM](https://github.com/VladT-PM) сторінка контакти перевірена без додаткової таски на чекбокс "політика конфіденційності" під контактною формою.
