### ISSUE TITLE
Employee Profile page/mistake correction

### ISSUE THREAD

**Issue by alinaivanishcheva** [it-volunteers-ukraine/ChariERP#378]
**Environment**

**Desktop (please complete the following information)**
OS: Windows 10 Pro v. 22H2
Browser: Google Chrome (v.125.0.6422.113)

**Pre-conditions**
https://chari-erp-dev-5jqgv.ondigitalocean.app/manager/employees - the form employee

**Description**
1.Mistake correction for the form employee "Данні для входу" 
2. Change the name "Дата вступу"

**Steps to reproduce**
1. Go to 'Employee Profile page...'
2. See a mistake for the form employee "Данні для входу" 

**Actual results**
Mistake correction for the form employee in the text "Данні для входу" 
Change the name "Дата вступу"

**Expected results**
Сorrect for the employee form in the text "Дані для входу" 
Change the name "Дата початку роботи"

**Screenshots** 
![2024-12-13_16h47_05](https://github.com/user-attachments/assets/c859a8c1-1856-4f89-aa19-80f4027819f6)

![Image](https://github.com/user-attachments/assets/307832fc-2fc8-4d8b-aa12-713061e0039e)
![Image](https://github.com/user-attachments/assets/4d368625-5107-42fc-b224-2303555e3de9)

**Comment by VladT-PM** [comment]
@VladDot, @alinaivanishcheva  Hi,
The "Дата вступу" input field is not a bug, as it aligned with the original requirements in Figma.
However, a decision was made to change it to "Дата початку роботи."
The Figma design has been updated, and the changes can now be implemented accordingly.
Thanks!

![Дата початку роботи](https://github.com/user-attachments/assets/d60c83fc-dc98-4fc5-9fd1-e713c94f6f3e)
