### ISSUE TITLE
То create an employee card

### ISSUE THREAD

**Issue by VladT-PM** [it-volunteers-ukraine/ChariERP#97]
Link to the page:
https://www.figma.com/design/al3AkjUmEzr5QEJjKIKkOm/Chari-New?node-id=5061-53549&t=Ylnl0ti3rWKNU9Eo-4

The card should be assembled according to the layout:

![Image](https://github.com/user-attachments/assets/e5d81954-fc90-4bd2-86db-3a6cde4f1ffb)

**Comment by KatyPupa** [comment]
@VladT-PM, @ASGladchenko, please,Explain what is the way to create an employee card:
- Through super admin. 
- through registration of a new organization?

**Comment by KatyPupa** [comment]
https://chari-erp-dev-5jqgv.ondigitalocean.app/manager/employees
