### ISSUE TITLE
To collect cards

### ISSUE THREAD

**Issue by VladT-PM** [it-volunteers-ukraine/ChariERP#99]
Link to the page:
https://www.figma.com/design/al3AkjUmEzr5QEJjKIKkOm/Chari-New?node-id=5061-53549&t=0pqkR85kJbQbEu4l-4

Cards should be collected according to their layout and adaptive:

![Image](https://github.com/user-attachments/assets/67ad4715-3d01-42cd-8dee-71660b9f2b7a)

**Comment by ASGladchenko** [comment]
close by #97

**Comment by alinaivanishcheva** [comment]
how to create a number of cards to check the collection for this task? @ASGladchenko @VladT-PM
